### ISSUE TITLE
Load all other pull requests when holding Ctrl or Alt and clicking "Load More"

### ISSUE THREAD

**Issue by Calinou** [EricEzaM/godot-github-overview#6]
To search through pull request titles with <kbd>Ctrl + F</kbd> easily, all pull requests need to be loaded. Right now, you need to click the **Load More** button at the bottom of the page a lot of times to do so.

This could be made easier and faster by loading until there's nothing left to load if the user holds <kbd>Ctrl</kbd> or <kbd>Alt</kbd> and clicks the **Load %ore** button.

**Comment by EricEzaM** [comment]
Closed in 9508aca4129d8696d9afae3400a36ef81a2cfd01
