### ISSUE TITLE
Page is outdated due to Actions being suspended for inactivity

### ISSUE THREAD

**Issue by Calinou** [EricEzaM/godot-github-overview#7]
The page was last updated on 2021-10-14 (almost 2 months ago as of writing). GitHub Actions disables scheduled actions after 60 days have passed without any commits on the repository. They can be re-enabled by pushing a commit or pressing a button on the repository's **Actions** tab.

@EricEzaM You should see a button on the repository's **Actions** tab that you can click to resume actions for 60 more days. Can you click it, please? Thanks in advance :slightly_smiling_face:

**Comment by EricEzaM** [comment]
Oops! Thanks :) Done
